### ISSUE TITLE
Fetch Stash credentials from Global Credentials support

### ISSUE THREAD

**Issue by christiangalsterer** [nemccarthy/stash-pullrequest-builder-plugin#1]
It would be nice if the credentials needed to fetch the PR information from Stash could be configured in Global Credentials and the plugin fetches the information from there. This is especially relevant where different users have different roles and Jenkins Bot user password shall not be known to all users who configured Jenkins jobs.

**Comment by nemccarthy** [comment]
Yeah this is a good idea. Will find some time for this soon. In the mean time happy to accept PRs :)

**Comment by pnathan** [comment]
:+1: 

I have 100s of jobs and 100s of repos (not an unusual mid-size corporation situation).  I can't ask all my users to use a credential that they shouldn't even know (read access across the entire repository).

I'm not terribly expert in developing Jenkins plugins or I'd figure out how to do this and send in a PR.

**Comment by nemccarthy** [comment]
Still don't have time for this right now. Perhaps @christiangalsterer has the experience to add this functionality

**Comment by matthewbarr** [comment]
Decent chance that client certs could be allowed via the credentials plugin too. :)

**Comment by nemccarthy** [comment]
Started work on this in the #credentials-support branch - need to get it filling the jelly template. Could someone have a look. See if they can get that final part working. The backend wiring should be fine. Just need the template support.

**Comment by nemccarthy** [comment]
This should be now fixed in PR #21 

Pushed as v1.3.0 to jenkins, should be there in a few hrs

**Comment by szpak** [comment]
The change seems to be reverted in master. That issue could be reopened to be easily found by newcomers.

**Comment by nickbroon** [comment]
Hopefully https://github.com/nemccarthy/stash-pullrequest-builder-plugin/pull/26 will return this functionality.
