### ISSUE TITLE
Option to mark the pull-request “needs work” on build failures

### ISSUE THREAD

**Issue by sabberworm** [nemccarthy/stash-pullrequest-builder-plugin#105]
The 4.2 API provides PUT on [/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/participants/{userSlug}](https://developer.atlassian.com/static/rest/bitbucket-server/4.6.2/bitbucket-rest.html#idp3111040]) to change a user’s approval status.

If the configured user would add itself as a reviewer and set its status to `"NEEDS_WORK"` before building and approve only on successful builds, it would be an easy way to disable the merge buttons until the build has succeeded.

**Comment by Adonai** [comment]
You can take my code that supports that from here
https://gitlab.com/Kanedias/StashPrBuilder

(All credits to @nemccarthy )

**Comment by sabberworm** [comment]
Duplicate of #107
