### ISSUE TITLE
Release 1.7.1 missing

### ISSUE THREAD

**Issue by PierreBtz** [nemccarthy/stash-pullrequest-builder-plugin#109]
Hello,

It seems there is a release in the jenkinsci/stash-pullrequest-builder-plugin (1.7.1), that is not available in this repository (which is still at 1.7.0). This means, the latest release of the plugin is not available in Jenkins. 

I made a fix that is available in the 1.7.1 release (#86), do you think it would be possible to make the release available?

Thanks in advance
Pierre

**Comment by mpender** [comment]
It would be great to get this available, seeing similar issue with stash comment phrase not triggering subsequent builds

**Comment by PierreBtz** [comment]
Hello @nemccarthy , do you have a feedback on this issue?

Thanks
Pierre

**Comment by nemccarthy** [comment]
Sorry, looks like the release must have failed. Will call this update ASAP Build only if Stash reports no conflicts

**Comment by mpender** [comment]
@nemccarthy , look forward to seeing it there soon

**Comment by nickbroon** [comment]
:+1:

**Comment by PierreBtz** [comment]
Hello @nemccarthy, it seems the last release of this plugin is a bit old and some really useful features are missing (like the support for pipeline jobs merged in January). Do you think you could also make a new 1.7.2 release containing everything?

Thanks
Pierre

**Comment by nemccarthy** [comment]
Please raise an issue here; https://issues.jenkins.io/browse/JENKINS-63802?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20stash-pullrequest-builder-plugin

Offical repo is here; Please raise PRs here https://github.com/jenkinsci/stash-pullrequest-builder-plugin

**Comment by PierreBtz** [comment]
Thanks for the feedback, not using the plugin anymore, indeed it was not in the proper repo, my bad.
