### ISSUE TITLE
Only run the jenkins job if the "test this please" phrase is in the comment

### ISSUE THREAD

**Issue by trevan** [nemccarthy/stash-pullrequest-builder-plugin#11]
I would like to create two types of pull request jobs.  One would run every time a pull request is created and modified and the other would only run if requested.  I'm thinking that if this plugin could be configured to only run if the "test this please" comment existed in stash, then I would be able to fire off the second job on an as needed basis.

It would also be nice to have PR #8 so that both jobs could have their own "test this please" comment.

**Comment by nemccarthy** [comment]
For now you can do this by setting a cron schedule that will never run. Would be nice to have this as a check box like say `Build on a schedule`, don't have the time ATM to work on this one, happy to take a PR! :) 

I'll merge in PR #8 and get a build out.

**Comment by nemccarthy** [comment]
If you add a check box, `Only build on comment` (default to false), then you should just be able to add an IF block before this line which if true would set the `shouldBuild = false` and leave the comment if to then set it back to true. This really needs to be cleaned up but this would be the quick and dirty. There is probably  story around only allowing certain users to request the build too... Anyway, leave that for another day... 

https://github.com/nemccarthy/stash-pullrequest-builder-plugin/blob/master/src/main/java/stashpullrequestbuilder/stashpullrequestbuilder/StashRepository.java#L167

**Comment by trevan** [comment]
ok, I'll look into that.

**Comment by nemccarthy** [comment]
coming in v1.1.0

**Comment by nemccarthy** [comment]
Version 1.1.0 Release. Should be in Jenkins Update Centre in a few hours.
