### ISSUE TITLE
Wishlist: Add environment variables to Jobs

### ISSUE THREAD

**Issue by rawler** [nemccarthy/stash-pullrequest-builder-plugin#13]
The GitHub pull-request plugin adds some useful Environment variables to the job, which enables some interesting tests to be performed. In our example, we would like to run static analysis on just the touched file of the commit, ensuring gradual improvement of code-quality. (Large code-base)

For that, we need something akin to "ghprbTargetBranch", to figure out which files is changed by this PR.

Could this be implemented?

**Comment by nemccarthy** [comment]
This is already the case. They should all come through as env vars... e.g. `echo $targetBranch` - see the README for the list.

![screen shot 2015-06-07 at 3 51 34 pm](https://cloud.githubusercontent.com/assets/8044836/8022793/3919f690-0d2d-11e5-8980-485d1f308eee.png)

There are also the standard GIT env vars... 
![screen shot 2015-06-07 at 3 51 59 pm](https://cloud.githubusercontent.com/assets/8044836/8022795/3bf14ddc-0d2d-11e5-9000-d9de34f9349f.png)

**Comment by nemccarthy** [comment]
I believe this has been fixed in PR #21 

Can you test v1.3.0
