### ISSUE TITLE
Can't cancel outdated pipeline jobs

### ISSUE THREAD

**Issue by wburgers** [nemccarthy/stash-pullrequest-builder-plugin#137]
Hi,

We are running version 1.7.1-SNAPSHOT of this plugin, which supports pipelines.
Pipeline builds are significantly faster in our case.
Outdated pipeline jobs are however not aborted when a new job is started.
Our queue grows rapidly as we have many PRs.

Can cancellation of outdated jobs get fixed?

If someone can tell me where to look, I will happily create a PR here.

**Comment by wburgers** [comment]
Since @nemccarthy is not maintaining this repo anymore, I created a groovy script to kill outdated jobs.
It can be found [here](https://gist.github.com/wburgers/c42c24d8c843088f1b1fdd027762701d)

**Comment by nemccarthy** [comment]
Please raise an issue here; https://issues.jenkins.io/browse/JENKINS-63802?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20stash-pullrequest-builder-plugin

Offical repo is here; Please raise PRs here https://github.com/jenkinsci/stash-pullrequest-builder-plugin
