### ISSUE TITLE
Stash notifier plugin link is broken in README

### ISSUE THREAD

**Issue by BearAlliance** [nemccarthy/stash-pullrequest-builder-plugin#138]

**Comment by aakshih** [comment]
When a pull request is created in bitbucket jenkins build does not get triggered. PullrequestID and other parameters are ot passed from bitbucket pull request to jenkin job. I see in log below Exception.

Jul 16, 2018 10:50:00 AM org.apache.commons.httpclient.HttpMethodDirector processWWWAuthChallenge
INFO: Failure authenticating with BASIC 'Atlassian Bitbucket'@bitbucketdc.*******.net:443
Jul 16, 2018 10:50:00 AM stashpullrequestbuilder.stashpullrequestbuilder.stash.StashApiClient$1 call
SEVERE: Failing to get response from Stash PR GET/rest/api/1.0/projects/SCPPAR/repos/asset-record/pull-requests
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Didn't get a 200 response from Stash PR GET! Response; 'Unauthorized' with message; null

Let me know how to fix this.

**Comment by nemccarthy** [comment]
Please raise an issue here; https://issues.jenkins.io/browse/JENKINS-63802?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20stash-pullrequest-builder-plugin

Offical repo is here; Please raise PRs here https://github.com/jenkinsci/stash-pullrequest-builder-plugin
