### ISSUE TITLE
Pipeline support?

### ISSUE THREAD

**Issue by an-sush** [nemccarthy/stash-pullrequest-builder-plugin#145]
Does this plugin support pipeline? Readme doesn't talk about it. If someone has done, please share snippets. Many thanks

**Comment by batmat** [comment]
See https://github.com/nemccarthy/stash-pullrequest-builder-plugin/issues/158 for actual repo.

**Comment by nemccarthy** [comment]
Please raise PRs here https://github.com/jenkinsci/stash-pullrequest-builder-plugin
