### ISSUE TITLE
JENKINS-52818 breaks build URL on Stash updates

### ISSUE THREAD

**Issue by Alex-Vol-SV** [nemccarthy/stash-pullrequest-builder-plugin#148]
The recent JENKINS-52818 changes cause this plugin to show this for each passing/failing build in Stash
```
[✓ BUILD SUCCESS]( PLEASE SET JENKINS ROOT URL FROM GLOBAL CONFIGURATION job/some-PR/18/) - Build #18 which took 35 min
```

The issue was the incorrectly referenced JenkinsLocationConfiguration which should not be instantiated but fetched with the static accessor.

I am submitting a PR with the fix.

**Comment by Alex-Vol-SV** [comment]
I have no control over this. I offered the pull request with the fix but I think this plugin is no longer maintained by @nemccarthy 

I created a private build for my CI environment with this fix and a few others cherry-picked from some of the open pull requests.

**Comment by rambrus** [comment]
oh, okay, I see. thanks for the info! I'll do the same.

**Comment by batmat** [comment]
See https://github.com/nemccarthy/stash-pullrequest-builder-plugin/issues/158

**Comment by nemccarthy** [comment]
Please raise in https://github.com/jenkinsci/stash-pullrequest-builder-plugin this is being maintained. If you would like to be a collaborator you can apply with jenkins org and there should be maintainers already looking after the repo in the official jenkins org.
