### ISSUE TITLE
Basic Auth username not respected

### ISSUE THREAD

**Issue by lavaman** [nemccarthy/stash-pullrequest-builder-plugin#15]
So I got the plugin working, but when I added more jobs for the rest of my repos, they all started using a basic auth user of 'Atlassian Stash' instead of the user I've specified in the jobs (jenkins).

**Comment by nemccarthy** [comment]
You need to configure the user/password for every single build job in jenkins... It seems to work fine for us here... Not sure where that username is coming from...

**Comment by lavaman** [comment]
Yeah I know. It changed even for the working jobs. Really strange. I'll let
you know if I figure out why.

**Comment by lavaman** [comment]
So it appears there were login failures for the jenkins user in stash that triggered the captcha. When I cleared the captcha, things started working again.
