### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by dreis2211** [nemccarthy/stash-pullrequest-builder-plugin#150]
Hi,

is this project still alive? @nemccarthy 

Cheers,
Christoph

**Comment by jakub-bochenski** [comment]
Looks dead, c.f https://issues.jenkins-ci.org/browse/JENKINS-55148

**Comment by jakub-bochenski** [comment]
https://groups.google.com/forum/?nomobile=true#!topic/jenkinsci-dev/oRBRP5-sZe4

**Comment by batmat** [comment]
Please also see https://github.com/nemccarthy/stash-pullrequest-builder-plugin/issues/158

This repo is deprecated AFAIU.

**Comment by batmat** [comment]
As a general rule, **every** plugins available from the main update center are expected to have their code hosted under https://github.com/jenkinsci

If not, then this is *very* likely fishy, and a dangerous plugin to install.

**Comment by nemccarthy** [comment]
Yes please no longer use this repo. Readme has been updated to point people to the offical jenkins org.
