### ISSUE TITLE
Post Build Comment doesn't work with multi-configuration projects

### ISSUE THREAD

**Issue by proski** [nemccarthy/stash-pullrequest-builder-plugin#156]
Only standard messages are posted for multi-configuration projects. The "Post Build Comment" settings are ignored. Jenkins 2.138.3, all plugins up-to-date.

**Comment by batmat** [comment]
Unmaintained repo, unrelated to the Jenkins Project FYI.
See https://github.com/nemccarthy/stash-pullrequest-builder-plugin/issues/158

**Comment by proski** [comment]
There is no "Issues" tab on https://github.com/jenkinsci/stash-pullrequest-builder-plugin so I can only report the issue here or in some other places (gitter, https://wiki.jenkins.io/display/JENKINS/Stash+pullrequest+builder+plugin etc). Please advise what would be the right place.

The issue is related to Jenkins and to stash-pullrequest-builder-plugin. The "Post Build Comment" feature is mentioned in `README.md`. The label is defined in `StashPostBuildComment.java`.

**Comment by proski** [comment]
Closing this issue in favor of https://issues.jenkins-ci.org/browse/JENKINS-55853
