### ISSUE TITLE
Delete this repository?

### ISSUE THREAD

**Issue by batmat** [nemccarthy/stash-pullrequest-builder-plugin#158]
Hello!

I'm a Jenkins core maintainer, and I just saw that this repository is still being pointed to by people, and new issues filed despite https://github.com/jenkinsci/stash-pullrequest-builder-plugin has been forked and I understand maintenance should be happening there.

I guess given this repo is unmaintained, it would be better off deleting this repo so https://github.com/jenkinsci/stash-pullrequest-builder-plugin is seen as the canonical one?

Thanks!

**Comment by jimklimov** [comment]
I'd rather not "delete" it as a number of PRs originally posted against this repo are still of interest. But maybe archiving it into read-only mode (and bannering this state in description on top bar) would make sense.

**Comment by batmat** [comment]
As an intermediate state. Why not. 

If you can get access here, which seems quite unlikely :/

**Comment by nemccarthy** [comment]
I'll let people know to move their requests to the Jenkins one!
