### ISSUE TITLE
Comments trigger a new build

### ISSUE THREAD

**Issue by emmaguy** [nemccarthy/stash-pullrequest-builder-plugin#23]
Hey,

This plugin works great for us, but with one exception - when someone raises a pull request and there are comments left, the plugin seems to detect this as a change and does another build. This then causes quite a lot of noise/emails when really we only want it to build when it's raised and then again if there's another push.

Am I missing something with the configuration?

**Comment by nemccarthy** [comment]
@emmaguy doesn't sound like the right behaviour. If there is a comment "test this please" then it will rebuild the PR. Are your comments in order? Does it happen with all pul requests? Which version of Stash & the plugin are you using? 

Try setting the phrase to something random. Could you post some screenshots of the comments and your plugin configuration

**Comment by emmaguy** [comment]
Jenkins v1.613, Plugin is v1.2.0. I haven't changed the phrase to rebuild the PR, perhaps it's because it's empty? Yeah, this happens on all PRs

![screen shot 2015-06-25 at 9 31 50 am](https://cloud.githubusercontent.com/assets/1143801/8350413/67054b2e-1b1d-11e5-8bd2-7efa3054645a.png)

I'll try setting the phrase. Any other thoughts would be appreciated. Thanks!

**Comment by emmaguy** [comment]
Having a non empty phrase seems to be better :smile: :+1:  Thanks!
