### ISSUE TITLE
Approve pull request

### ISSUE THREAD

**Issue by jesavro** [nemccarthy/stash-pullrequest-builder-plugin#24]
Can this module approve pull requests as well?

Thank you
Avi

**Comment by laurentverbruggen** [comment]
No it can't, but why would you want to automate approvals? It seems simply disabling a required number of approvals does the same thing...

**Comment by jesavro** [comment]
We have various stages of approvals. I would like to have automated tests provide the first approval.

**Comment by nemccarthy** [comment]
Happy to take a PR on this one. You could make the Jenkins user in Stash an approver and say require a minimum of two approvals. There is a rest api for this. It shouldn't be too hard to add

**Comment by nemccarthy** [comment]
If you are using the stash notifier plugin you can set the number of required builds to be >= 1. This has the same effect. As soon as the PR build is done, stash will be notified for that commit and you will have 1 successful build. If you set the number of builds as a PR gate it seems to make more sense and achieve the same effect.
See the instructions on the integration between this plugin and the stash notifier plugin.
If you want to do an approval, it still would be possible, happy to take a PR on this one, however closing this issue for now
