### ISSUE TITLE
Plugin not polling Stash

### ISSUE THREAD

**Issue by Lastly** [nemccarthy/stash-pullrequest-builder-plugin#28]
Hi, I have a Jenkins instance where this handy plugin is not polling stash.  The job has is configured with a cron set to every minute (```* * * * *```), but it does not look for new pull requests as they are created/updated.  The kicker is that everything works great when Jenkins is restarted; with the job connecting to Stash, reading the comments to kick off a build, and reporting results back.  After looking at the logs it appears that the plugin is not polling correctly if at all.  Every once in a while (at seemingly random times, sometimes hours, sometimes minutes apart) the logs will show ```BuildListener onStarted called.```  and nothing following that.  After a restart the logs are populated as expected with request messages and statements that look correct.  Any ideas on what may be going on?

**Comment by Lastly** [comment]
Uncovered the base issue.  I had two jobs using the pr-builder (different repos and users) one of which was only stubbed out and in-progress.  The half-finished job would put out a message about an error in credentials, but somehow this error must not be handled as it affected my other running job as well, causing polling to never start.

**Comment by nemccarthy** [comment]
that doesn't seem good. it should work fine if all the credentials are correct?

**Comment by Lastly** [comment]
Yes, the plugin will work correctly when the job with failing credentials is disabled (or deleted).  The way I see it, an error in one job should not be able to 'cross over' to another, especially when it kills the plugin for all other jobs.

**Comment by nemccarthy** [comment]
Should be fixed in 1.5
