### ISSUE TITLE
[TEST] Test task is failing

### ISSUE THREAD

**Issue by williamsbdev** [nemccarthy/stash-pullrequest-builder-plugin#30]
@nemccarthy thank you for this awesome plugin. I just forked this repo and was running the test task and I have 2 failing tests for the 8 tests in the project. I have did a fresh pull and I am running Maven 3.3.1 and Java 1.8.0_25. Can you confirm that the tests are failing for you as well?

**Comment by nemccarthy** [comment]
You can't run with Java 8. Set your JAVA_HOME to a Java 7 path before running maven.

**Comment by benkiefer** [comment]
[Java 7 is end of life](https://www.java.com/en/download/faq/java_7.xml).

I threw a [PR](https://github.com/jenkinsci/stash-pullrequest-builder-plugin/pull/7) out there on the main jenkinsci project. Should I have put one out here for this?

**Comment by nemccarthy** [comment]
Thanks ill put this in 1.5 release
