### ISSUE TITLE
Doesn't queue the PR builds on the same project, only builds the newest

### ISSUE THREAD

**Issue by tldavies** [nemccarthy/stash-pullrequest-builder-plugin#31]
We currently pull every 5 minutes to see if a PR is created. When we have to 2 different PRs on the same project with different branches created/updated with in the same 5 minutes it only builds the latest PR.

Need it to queue all PR builds that it finds. Not just the latest. As we can create/update multiple PRs between pulls.

**Comment by nemccarthy** [comment]
Currently it should just queue each request on each poll. Happy to take a PR on this one. The other option is to increase the polling time so you don't have to wait as long between requests.

**Comment by tldavies** [comment]
Even if we upped the the polling it would still miss PRs if 2 people commit to 2 different PRs on the same branch at the same time, which is very common towards the end of the sprint. -- the most interesting we have had with this is that it says it is starting PR 54 but it pull PR 55 code. So the links dont match the code. 

We also have 35+ jobs polling from our Jenkins servers which is why we don't poll more. 

Also just to confirm it is only able to get one PR update per project for each time it polls?

**Comment by hoto** [comment]
we have got the same issue
whn we have 2 PR in one repo, this plugin says it is building PR #1 but in log we see it actually take commit from PR #2

**Comment by nemccarthy** [comment]
This should be fixed in 1.5
