### ISSUE TITLE
Force the refs to be updated

### ISSUE THREAD

**Issue by Karmaki** [nemccarthy/stash-pullrequest-builder-plugin#32]
I experimented strange behaviors because in some cases, the plug-in was able to detect a new PR, but not to checkout the correct branch. I asked here : http://stackoverflow.com/questions/31458668/why-is-there-a-delay-between-a-pull-request-and-the-possibility-to-fetch-it-in, and someone from Stash explained the reason. It seems that you should call ``PullRequestService.canMerge `` before fetching. What do you thing ?

A temporary workaround is to force the update by exploring the PR in the UI, but it is not very convenient.

**Comment by nemccarthy** [comment]
I think we added this option already - check the Build only if PR is mergeable? & Build only if Stash reports no conflicts? options

**Comment by Karmaki** [comment]
OK. Thank you very much for your quick answer. I'll check these two options then.
Many thanks for your great plug-in too !
