### ISSUE TITLE
Cannot use ssh or https in 	the "Stash Host" field ?

### ISSUE THREAD

**Issue by Karmaki** [nemccarthy/stash-pullrequest-builder-plugin#33]
I used this plug-in with a dummy stash installation, and it is working well, but the access used ``http``.
Not, I am going back to my real project.
My git repository URL looks ``ssh://git@git.<stashURL>:7999/<project>/<repo>.git`` and it is working well. But I want to use the plugin (1.3.1 version), I cannot manage to find what to put in the``Stash Host`` field.
- I had ``java.lang.IllegalStateException: unsupported protocol: 'ssh' ``
- I also had ``Unrecognized SSL message, plaintext connection?`` 
- ``git.<stashURL>:7999`` gives ``java.lang.IllegalStateException: unsupported protocol``
- ``https://git.<stashURL>:7999`` gives ``java.lang.NullPointerException``
- I also tried with nothing in the field, hoping it will be able to get it from the git URL, but it gives ``java.lang.IllegalArgumentException: host parameter is null``

What am I supposed to put here in this case ? Is this supported ?
Thanks in advance for your help.

**Comment by Karmaki** [comment]
Sorry for the duplicate, this seems to be the same bug than #22.

**Comment by nemccarthy** [comment]
The stash host must be a HTTPS or HTTP URL. You CANNOT use ssh. This is the URL for the Stash REST API!!! 

Make sure your SSL certificates are valid, if not add the CA as trusted on your jenkins machine. There is a PR which allows you to ignore SSL. We use this with https every day without a problem.
