### ISSUE TITLE
Comments URL Has Changed

### ISSUE THREAD

**Issue by randyesq** [nemccarthy/stash-pullrequest-builder-plugin#34]
I upgraded to plugin 1.3.1 after seeing this error in the logs:

````
Jul 22, 2015 10:35:02 AM FINEST stashpullrequestbuilder.stashpullrequestbuilder.stash.StashApiClient
PR-POST-REQUEST:http://stash.us.com/rest/api/1.0/projects/CMS/repos/imps/pull-requests/129/comments with: [*BuildStarted* **IMPS_pull_request**] ec91d4b382a46fb46d5d9401f9e61c2e0d995987 into 0d3a6d03ba29d01a0caba1deaaf77a15f4acd987
Jul 22, 2015 10:35:02 AM INFO stashpullrequestbuilder.stashpullrequestbuilder.stash.StashApiClient postRequest
API Request Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://stash.us.com/rest/api/1.0/projects/CMS/repos/imps/pull-requests/129/comments">here</a>.</p>
<hr>
<address>Apache/2.2.12 (Linux/SUSE) Server at stash.us.com Port 80</address>
</body></html>
````

The error still persists in 1.3.1. My stash instance no longer receives any comments, or any other interaction for that matter and the Jenkins job does not run. I am not sure how to find the version number of my stash instance, although the REST API URL says 1.0.

**Comment by randyesq** [comment]
Any  help available on this?

**Comment by nemccarthy** [comment]
You are using a http url for your stash host. Please use a http**s**:// URL in stash host setting! 

Your stash host is correctly trying to redirect you to HTTPS as you would expect. You shouldn't be using basic over http!

**Comment by randyesq** [comment]
Thanks!
