### ISSUE TITLE
Variable ${pullRequestCommit} was removed

### ISSUE THREAD

**Issue by dylankiss** [nemccarthy/stash-pullrequest-builder-plugin#37]
The documentation states that when using the "Notify Stash Instance" post-build step, you should use the variable `${pullRequestCommit}` as Commit SHA-1 value.
However that variable has been removed in the latest release.
Is there a specific reason for this, or could you just bring that variable back?
It would be much appreciated.

**Comment by thalesac** [comment]
+1 on this.. There is a reason why this was reverted?

https://github.com/jenkinsci/stash-pullrequest-builder-plugin/commit/9288db11a72b5527addbb822df3d0a43587898c0

**Comment by indrgun** [comment]
What is the variable to out as Commit SHA-1 value in the meantime?  Was it there in v1.3.0?  I used latest v1.3.1.

**Comment by nemccarthy** [comment]
Adding this one back in

**Comment by tobybro** [comment]
I just upgraded to 1.4.1 and I am still not seeing the ${sourceCommitHash} get set.

**Comment by Cherum** [comment]
We're on 1.4.2 and the variable is not set. What's the status of this?

**Comment by nemccarthy** [comment]
This should be set and is working in 1.4.2 of the plugin. Please make sure you use; `$sourceCommitHash` in the notify stash plugin.

**Comment by PixnBits** [comment]
@Cherum I have the same issue, I think #89 has the fix due to [SECURITY-170](https://jenkins.io/blog/2016/05/11/security-update/)

**Comment by PixnBits** [comment]
@nemccarthy FWIW this is an issue again due to SECURITY-170 and instances that don't set `hudson.model.ParametersAction.keepUndefinedParameters` or `hudson.model.ParametersAction.safeParameters`
I'm hoping #89 has the fix so we can use `$sourceCommitHash ` again 🙏
