### ISSUE TITLE
If there are more than 25 open pull requests - builds are not triggred for pull requests beyond 25th

### ISSUE THREAD

**Issue by mkj28** [nemccarthy/stash-pullrequest-builder-plugin#39]
We had a maintenance and restarted jenkins - after that jobs that were triggered by the plugin no longer are. Nothing apparent changed on the jobs/jenkins or stash side. Logs are not very conclusive to me (see below). The plugin is triggered every minute as before.

Aug 19, 2015 10:42:00 PM INFO stashpullrequestbuilder.stashpullrequestbuilder.StashPullRequestsBuilder run
Build Start.
Aug 19, 2015 10:42:00 PM INFO stashpullrequestbuilder.stashpullrequestbuilder.StashRepository getTargetPullRequests
Fetch PullRequests.
Aug 19, 2015 10:42:01 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:02 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:02 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:02 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:03 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:03 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:03 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:03 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:04 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:04 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:04 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:05 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:05 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:05 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:06 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:06 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:06 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:06 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:07 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:07 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:08 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:08 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:08 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:09 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:09 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:09 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:09 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:10 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:10 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:10 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:11 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:11 PM WARNING org.apache.commons.httpclient.HttpMethodBase getResponseBody
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Aug 19, 2015 10:42:11 PM INFO stashpullrequestbuilder.stashpullrequestbuilder.StashBuildListener onStarted
BuildListener onStarted called.
Aug 19, 2015 10:42:11 PM INFO stashpullrequestbuilder.stashpullrequestbuilder.StashBuildListener onStarted
BuildListener onStarted called.

**Comment by mkj28** [comment]
Looks like maybe it is because we have more than 25 Pull Requests? I'm looking at https://developer.atlassian.com/static/rest/stash/3.5.0/stash-rest.html and there is a limit parameter that defaults to 25 if not set.

**Comment by mkj28** [comment]
OK confirmed that is it - after closing some pull requests - the job started working. 
Is the limit configurable on the plugin side by any chance? Or is there a way to enable pagination?

**Comment by szpak** [comment]
That;s a known issue with existing PR - see https://github.com/nemccarthy/stash-pullrequest-builder-plugin/pull/38,

**Comment by nemccarthy** [comment]
Should be fixed in 1.4
