### ISSUE TITLE
Didn't get a 200 response from Stash PR POST

### ISSUE THREAD

**Issue by warrickhill** [nemccarthy/stash-pullrequest-builder-plugin#49]
I don't understand why I'm getting this error, the 'started build' commet gets created ok but because the plugin doesn't get a 200 response from stash the build never happens

The error log says the response is ```'Created' with message; {"id":256,"version":0,"text":"[*BuildStarted* **test-jenkins-PR**] 81c0256c157649c31daed0333de6add965f744c9 into 5471d06841458a84deb9d1c20d29289c3165d315"...```

According to the stash Documentation a successful PR comment post will return a 201 response header
https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp1448560

**Comment by SagaciousZed** [comment]
I am also experiencing the symptoms with our setup currently.

**Comment by nemccarthy** [comment]
Sorry, this was a bug introduced in 1.4.1. Please upgrade to 1.4.2

**Comment by aakshih** [comment]
When a pull request is created in bitbucket jenkins build does not get triggered. PullrequestID and other parameters are ot passed from bitbucket pull request to jenkin job. I see in log below Exception.

Jul 16, 2018 10:50:00 AM org.apache.commons.httpclient.HttpMethodDirector processWWWAuthChallenge
INFO: Failure authenticating with BASIC 'Atlassian Bitbucket'@bitbucketdc.*******.net:443
Jul 16, 2018 10:50:00 AM stashpullrequestbuilder.stashpullrequestbuilder.stash.StashApiClient$1 call
SEVERE: Failing to get response from Stash PR GET/rest/api/1.0/projects/SCPPAR/repos/asset-record/pull-requests
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Didn't get a 200 response from Stash PR GET! Response; 'Unauthorized' with message; null

Let me know how to fix this.
