### ISSUE TITLE
need to build each PR into a seperate jenkins workspace subfolder is this possible?

### ISSUE THREAD

**Issue by timomayer** [nemccarthy/stash-pullrequest-builder-plugin#50]
first of all thanks for the great plugin.
i need to build each PR into a seperate jenkins workspace subfolder is this possible?

**Comment by nemccarthy** [comment]
Should be possible. Could you pass in a environment variable to do this? How do you imagine this would work. We added parameters support in 1.4.1 which if you manually kick off the PR would allow you to build it in a folder of your choosing. You could always use the SHA of the commit hash of the PR and make this the folder name? Its exposed as a variable you can use in your jenkins jobs, would that work?

**Comment by nemccarthy** [comment]
Other option would be to use the from or to branch name. This would be super simple as its exposed an an env var
