### ISSUE TITLE
Allow suppressing "Build started" and "Build success"/"Build failed"

### ISSUE THREAD

**Issue by akhaku** [nemccarthy/stash-pullrequest-builder-plugin#53]
For cases where we have an alternate method of reporting the result of a build, it would be nice to suppress the stash-pullrequest-builder-plugin build comments. My use case: I have a script that is triggered by a jenkins job, which comments back on the PR with the result of a javascript lint. The comments from this plugin are unnecessary noise at that point - there are probably other cases where this is applicable, too.

I can put up a PR for this myself - let me know if you think this is a desirable feature? It would be configurable in jenkins, and the suppression would be opt-in.

**Comment by indrgun** [comment]
HI Akhaku,

I am interested in your suggested issue.  Our use case is similar such that I image we have several Jenkins Job #1 each configured with the plugin to poll from a Git/Stash repository.  They in turn will trigger 1 instance of Jenkins Sanity Job that takes the PR information as parameters from Jenkins Job #1.  We want the Sanity Job #2 to does the clone, run sanity test and report back to Stash to indicate whether it fails or passes.

I guess I want Sanity to post the comment back to Stash about the start of Sanity, and Sanity completion.

**Comment by nemccarthy** [comment]
Looks like we have 2 PRs on this now #52 & #54

**Comment by nemccarthy** [comment]
Will add this as a feature in the 1.5 release
