### ISSUE TITLE
Variable ${pullRequestCommit} is not set

### ISSUE THREAD

**Issue by Cherum** [nemccarthy/stash-pullrequest-builder-plugin#56]
As described in this thread, the variable ${pullRequestCommit} is not set: https://github.com/nemccarthy/stash-pullrequest-builder-plugin/issues/37

According to the answer this should be in the current release, but we have the same problem with the 1.4.2 release.

**Comment by nemccarthy** [comment]
This should be set and is working in 1.4.2 of the plugin. Please make sure you use; `$sourceCommitHash` in the notify stash plugin.
