### ISSUE TITLE
Branches with slashes confuse the job

### ISSUE THREAD

**Issue by trevan** [nemccarthy/stash-pullrequest-builder-plugin#6]
I have a branch named "bugfix/fix-a-bug" and when I created a pull request, this plugin correctly started a build.  But then it failed because it couldn't find any changes to the branch.  It turns out that it was using "fix-a-bug" as the branch name instead of "bugfix/fix-a-bug".

This plugin needs to handle branches that have '/' in them.

**Comment by nemccarthy** [comment]
Yeah, seems a problem with the branch passing. There is PR #7 in which should fix this. I'll cut 1.0.1 sometime tonight so it should be in Jenkins repo within 24 hours.

**Comment by nemccarthy** [comment]
@trevan 1.0.1 released with this fix. Should appear in Jenkins updates in the next 6 or so hours.

**Comment by trevan** [comment]
It's working for me now.  Thanks.
