### ISSUE TITLE
Dependencies on other pull requests?

### ISSUE THREAD

**Issue by jcogilvie** [nemccarthy/stash-pullrequest-builder-plugin#64]
My team is using a gradle/mavenish workflow where we have internal libraries that have their own jenkins builds.  

Sometimes, when we commit a change, it's dependent on something upstream being merged first.  Is it possible to add support for dependent pull requests?  I.e., "don't try to build this PR until the following PRs have merged"?

**Comment by indrgun** [comment]
PR is specific to a particular git repository.  I think this plugin polls a
single git on stash for new PR.  You can make the upstream to use this
plugin then triggers the downstream.  The downstream though can't no longer
use the plugin.  You have to feed it with parameter about git repo and the
PR #.

**Comment by jcogilvie** [comment]
I would expect this to work either by indicating the PR # in the commit message or in a comment on the downstream PR.  

Gerrit is able to do this by using change identifiers in commit messages, which can be established by git hooks.  Maybe this plugin could parse those from commit messages if the clients were using the gerrit hooks?

**Comment by nemccarthy** [comment]
This would be a new feature, seems like a pretty specific work flow, happy to take PR to add a new feature to this plugin.

**Comment by nemccarthy** [comment]
Closing this one for now. Happy to take a contribution
