### ISSUE TITLE
Enhancement: Update/Removed queued builds for PR

### ISSUE THREAD

**Issue by nickbroon** [nemccarthy/stash-pullrequest-builder-plugin#70]
If a PR is updated (which might happen often if rebuild if target branch changes option is used, or builds take a long time) it would be better to search the build queue for any queued jobs matching that PR and either update it or remove the queued job before adding a new one. That is to say there should only be one queued build per PR, as only the most recent is usually of interest.
There are API that should make this possible, that can be called before `job.scheduleBuild2`. `isInQueue` and `getQueueItem` look the most relevant.

**Comment by mandrizzle** [comment]
I can make a pr for this but it only works for queued items at the moment. I have not found a way to cancel a running jobs yet.

**Comment by nickbroon** [comment]
I think cancelling queued items is sufficient.

**Comment by mandrizzle** [comment]
Figured out how to cancel running jobs too!

**Comment by nickbroon** [comment]
Resolved by #83

**Comment by nemccarthy** [comment]
Released in 1.7.0
