### ISSUE TITLE
Unstable builds are reported as failures in stash pull request comment

### ISSUE THREAD

**Issue by ecar** [nemccarthy/stash-pullrequest-builder-plugin#71]
After a build has been marked "unstable" in Jenkins, the pull request gets a comment that says "BUILD FAILURE". I would expect the comment to say "BUILD UNSTABLE".

**Comment by nemccarthy** [comment]
There is already a PR for this; https://github.com/jenkinsci/stash-pullrequest-builder-plugin/pull/12 

Will be in the next release. Should be out in a week or so.

**Comment by ecar** [comment]
Thanks for the quick reply. Great plug-in!

**Comment by nemccarthy** [comment]
Fixed in release 1.5.3, check for updates in Jenkins in a few hours
