### ISSUE TITLE
Option to not comment on pull request

### ISSUE THREAD

**Issue by gthicks** [nemccarthy/stash-pullrequest-builder-plugin#72]
I would like there to be an option to not comment on the pull request at all. In my use case, the comments from this plugin are redundant. I am happy to make the changes needed, but I would need someone to point me in the right direction. I am not certain where in the code the comments are being added.

**Comment by nemccarthy** [comment]
Help would be great, this is actually related to PR #52 
We need someone to finish of the serialisation work for the PR states. If you wanted to pick that up it would be great.

**Comment by gthicks** [comment]
I'll take a look at that issue, sorry for the duplicate.
