### ISSUE TITLE
Add the option of disabling comments

### ISSUE THREAD

**Issue by Macarse** [nemccarthy/stash-pullrequest-builder-plugin#81]
We are using the StashNotifier plugin and we don't need the comment.
Can it be disabled?

**Comment by nemccarthy** [comment]
#52 is where its at. Still needs persistence of the build state in Jenkins, otherwise all open PRs would trigger a new build on a jenkins restart. Need someone to do some work on this one. If you want grab that PR branch and get it working and I'll merge it in.
