### ISSUE TITLE
jenkins will fire endless builds if there is a (Parentheses) in the job's display name

### ISSUE THREAD

**Issue by XIALEX** [nemccarthy/stash-pullrequest-builder-plugin#85]
It's easy to reproduce, create a job with the usual setting with the PR plugin. 

Go to **Advanced Project Options** -> in **Display Name** type in 'Anything you want with a (Parentheses)', then it will fire a build every 2 minutes (assuming Cron set to H/2 * * * *)

**Comment by dalewking** [comment]
This is a duplicate of my bug #27 which I submitted with a patch for fixing it 11 months ago and is still not been incorporated.

**Comment by nemccarthy** [comment]
This has been fixed in 1.7
